# Generated by Django 6.0.3 on 2026-03-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_randompickhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='shared_with_couple',
            field=models.BooleanField(default=False),
        ),
    ]
