# Generated by Django 6.0.3 on 2026-03-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_place_shared_with_couple'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='favoriteplace',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='randompickhistory',
            options={'ordering': ['-picked_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='placetag',
            unique_together={('place', 'tag')},
        ),
    ]
