# Generated by Django 6.0.3 on 2026-04-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_category_options_alter_favoriteplace_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randompickhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
    ]
