# Generated by Django 6.0.3 on 2026-04-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_randompickhistory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randompickhistory',
            name='image',
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
    ]
