# Generated by Django 6.0.3 on 2026-05-08 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_remove_randompickhistory_image_place_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='favoriteplace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='area',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_visited',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='shared_with_couple',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='randompickhistory',
            name='picked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='places_cate_name_321934_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriteplace',
            index=models.Index(fields=['user'], name='places_favo_user_id_c973e6_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriteplace',
            index=models.Index(fields=['place'], name='places_favo_place_i_98a3da_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriteplace',
            index=models.Index(fields=['created_at'], name='places_favo_created_1a8b19_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriteplace',
            index=models.Index(fields=['user', 'created_at'], name='places_favo_user_id_9a4e94_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['user'], name='places_plac_user_id_fd75a9_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category'], name='places_plac_categor_4fa2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='places_plac_name_39c762_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['area'], name='places_plac_area_c03e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_public'], name='places_plac_is_publ_bb3f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['shared_with_couple'], name='places_plac_shared__cd7b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['created_at'], name='places_plac_created_6fc9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['user', 'created_at'], name='places_plac_user_id_8024a0_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['user', 'is_public'], name='places_plac_user_id_e8439c_idx'),
        ),
        migrations.AddIndex(
            model_name='placetag',
            index=models.Index(fields=['place'], name='places_plac_place_i_89e585_idx'),
        ),
        migrations.AddIndex(
            model_name='placetag',
            index=models.Index(fields=['tag'], name='places_plac_tag_id_5316b4_idx'),
        ),
        migrations.AddIndex(
            model_name='placetag',
            index=models.Index(fields=['place', 'tag'], name='places_plac_place_i_bd8d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='randompickhistory',
            index=models.Index(fields=['user'], name='places_rand_user_id_583429_idx'),
        ),
        migrations.AddIndex(
            model_name='randompickhistory',
            index=models.Index(fields=['place'], name='places_rand_place_i_ae6557_idx'),
        ),
        migrations.AddIndex(
            model_name='randompickhistory',
            index=models.Index(fields=['picked_at'], name='places_rand_picked__2bfbd7_idx'),
        ),
        migrations.AddIndex(
            model_name='randompickhistory',
            index=models.Index(fields=['user', 'picked_at'], name='places_rand_user_id_a30c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='places_tag_name_04bcd9_idx'),
        ),
    ]
