# Generated by Django 6.0.3 on 2026-05-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_nickname_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', '一般使用者'), ('couple', '情侶使用者'), ('admin', '管理員')], default='user', max_length=20),
        ),
    ]
