# Generated by Django 6.0.3 on 2026-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_alter_memory_place_alter_memory_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='shared_with_couple',
            field=models.BooleanField(default=False),
        ),
    ]
