# Generated by Django 6.0.3 on 2026-04-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_memory_shared_with_couple'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
