# Generated by Django 6.0.3 on 2026-03-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0002_couplerelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupleinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
