# Generated by Django 6.0.3 on 2026-03-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0003_alter_coupleinvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='couplerelationship',
            name='anniversary_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
